---
title: "Punch list for paper examples"
author: Erin Schuman, Matthew Kuperus Heun
date: "27 Aug 2025"
---

- [ ] MKH: get the paper to build
- [ ] clean up data repo
- [ ] Potential b_c example (large amount of b)
      (relevance of concentration exergy)
- [ ] b_c vs. N graph (need to decide if we want to include a graph like this)
- [ ] EES: irreversibilities for BXCC
- [ ] EES: check energy balances for the BCC
 -[ ] EES: Implement Q_loss into BXCC
- [ ] EES: Read the entire paper completely. Edit the nomenclature table.
- [ ] EES: Draft an abstract
- [ ] EES: Draft a conclusion
- [ ] EES: Figure out why iron ore processes have lower efficiency than
           limestone or coal processes
- [ ] EES: There are many processes in the economy where we do NOT trade
           exergy of energy for the exergy of materials.  
           The text in the introduction should allow for those processes, too.
- [ ] EES: In the introduction, highlight that we are defining
           material exergy as four components.
           We might be the first to do that.
- [ ] EES: Pull Table 2 forward into the introduction
- [ ] EES: Remove statepoint (k) from Table 1 (hierarchy table)
- [ ] EES: Add a statepoint definition in text: "A statepoint is a location in space
           where temperature, pressure, and composition of a material is known."
- [ ] EES: State that material exergy can be calculated 
           at a statepoint, for a mixture, for a compound, and/or for an element.
- [ ] EES: Clarify that material exergy can be calculated at a statepoint
- [ ] EES: Make clearer distinction between chemical exergy of a compound 
           and chemical exergy of a mixture.
- [ ] EES: For calculating chemical exergy, 
           make clearer distinction between compounds that exist in the reference environment
           and compounds that DO NOT exist in the reference environment.
           Refer to hierarchy.
- [ ] EES: Make clearer distinction between concentration exergy of a compound
           and concentration exergy of a mixture.
           Refer to hierarchy.
- [ ] EES: In chemical and concentration exergy sections, 
           talk about calculating for a compound or element first.
           Then talk about calculating for a mixture 
           (which is likely to be at a statepoint).
- [ ] EES: Do a better job of describing that the content of Section 3 
           is tied to the contributions of the paper.
           This should be done in both the intro
           (where we describe the contents of each section)
           and at the top of the results section (Section 3).
- [ ] EES: Do a better job (if necessary) of describing the contents of Section 4,
           namely that is describes additional analyses that can be performed
           when data are in the RUVY matrices of the PSUT framework.
           This should be done in both the intro
           (where we describe the contents of each section)
           and at the top of the discussion section (Section 4).

- [X] EES: No ~ for % units. Usually 15%, not 15~%.  Or 15~%/yr.
- [X] EES: Clean up all broken names in the name manager in Paper Examples.xlsx
- [X] Coke oven efficiencies should be lower 
- [X] Tidy up arrows 
- [X] MCC B RUVY nonzero energy balances
- [X] Name regions in MCC B RUVY R_B
- [X] Name regions in MCC m RUVY R_m
- [X] Add U_feed, U_EIOU matrices (same structure as **U**) for material and energy
- [X] Add r_EIOU matrix (ratio of EIOU to U, same structure as U, zero matrix)
- [X] Add S_units matrix (rows of energy carriers, same as rows of U matrix, column is units w/ entry as 1)
- [X] Add element balance to each process
- [X] b for fuels
- [X] h to [kJ/mol]
- [X] hM matrix
- [X] edit matrices
- [X] example appendix
- [X] Erin's laptop usable
- [x] fix warnings
- [x] Rotary kiln efficiencies should be higher 
